packages:
  - shared-config
  - indexer-envio
  - ui-dashboard
  - metrics-bridge

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@sentry/cli"
  - es5-ext
  - esbuild
  - rescript
