packages:
  - shared-config
  - indexer-envio
  - ui-dashboard
  - metrics-bridge
  - aegis
  - alerts/infra/onchain-event-handler
  - alerts/infra/scripts

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@mento-protocol/*"
  - envio-cloud
  - "@envio-dev/envio-cloud-*"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@nestjs/core"
  - envio-cloud
  - "@sentry/cli"
  - es5-ext
  - esbuild
  - rescript
