# Generate .env file for local development.
#
# Why `terraform_data` and not `local_file`: the `local_file` provider's Read
# function stats the on-disk file each refresh. On a fresh-checkout CI runner
# the file is absent (it's gitignored) so `terraform plan -detailed-exitcode`
# always returned 2, defeating the skip-when-no-changes gate in
# `.github/workflows/alerts-infra.yml`. `terraform_data` only re-evaluates
# `triggers_replace`, so CI plans exit 0 when inputs are unchanged.
#
# Local-dev contract is unchanged: `pnpm run generate:env` from this directory
# still rewrites `.env` with current values. Any input change replaces the
# resource and re-runs the provisioner automatically.

locals {
  env_file_content = <<-EOT
    # Generated by Terraform - do not edit manually
    # Regenerate with: pnpm run generate:env (from onchain-event-handler directory)

    # GCP Project Configuration
    GCP_PROJECT_ID=${var.project_id}

    # Multisig Configuration (JSON format, without notification destinations)
    MULTISIG_CONFIG=${jsonencode(local.multisig_config_for_json)}

    # Supported Chains (comma-separated)
    SUPPORTED_CHAINS=${join(",", local.chains)}

    # QuickNode Configuration
    QUICKNODE_SIGNING_SECRET=${var.quicknode_signing_secret}
    # Local development should not depend on or mutate the Terraform-managed
    # production replay bucket. Override this with a real bucket only when testing
    # replay persistence against GCS.
    QUICKNODE_REPLAY_BUCKET=local-quicknode-replay-nonces

    # Slack Configuration (shared across all multisigs)
    SLACK_BOT_TOKEN=${var.slack_bot_token}
    SLACK_CHANNEL_ALERTS=${local.shared_channel_ids.alerts}
    SLACK_CHANNEL_EVENTS=${local.shared_channel_ids.events}
  EOT
}

resource "terraform_data" "env_file" {
  triggers_replace = {
    content_hash = sha256(local.env_file_content)
  }

  # `umask 077` covers the create path; explicit `chmod 0600` after the
  # write enforces the mode on the truncate-rewrite path too (the `>`
  # redirect preserves the existing file's permissions, so an `.env`
  # created earlier with looser perms would otherwise keep them across
  # provisioner re-runs). Content is passed via env var to avoid shell
  # quoting pitfalls with embedded JSON / special characters.
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "umask 077 && printf '%s' \"$ENV_CONTENT\" > '${path.module}/.env' && chmod 0600 '${path.module}/.env'"
    environment = {
      ENV_CONTENT = local.env_file_content
    }
  }
}

# Detach the legacy `local_file.env_file` from state without deleting the
# on-disk file on developer machines. The new `terraform_data.env_file`
# resource above replaces it. Safe to remove this block after one apply
# cycle (state no longer references the old resource).
removed {
  from = local_file.env_file
  lifecycle {
    destroy = false
  }
}
