# Generate .env file for local development
# This file creates a .env file in the onchain-event-handler directory with all necessary
# environment variables derived from Terraform variables.
# Reuses locals from locals.tf to avoid duplication
# Run: terraform apply -target=module.onchain_event_handler.local_file.env_file
# or: npm run generate:env (from onchain-event-handler directory)
resource "local_file" "env_file" {
  filename = "${path.module}/.env"
  content  = <<-EOT
# Generated by Terraform - do not edit manually
# Regenerate with: terraform apply -target=module.onchain_event_handler.local_file.env_file
# or: npm run generate:env (from onchain-event-handler directory)

# GCP Project Configuration
GCP_PROJECT_ID=${var.project_id}

# Multisig Configuration (JSON format, without webhooks)
MULTISIG_CONFIG=${jsonencode(local.multisig_config_for_json)}

# Supported Chains (comma-separated)
SUPPORTED_CHAINS=${join(",", local.chains)}

# QuickNode Configuration
QUICKNODE_SIGNING_SECRET=${var.quicknode_signing_secret}

# Discord Webhook URLs (shared across all multisigs)
DISCORD_WEBHOOK_ALERTS=${local.shared_webhook_urls.alerts}
DISCORD_WEBHOOK_EVENTS=${local.shared_webhook_urls.events}
  EOT
}

