# Generate .env file for local development
# This file creates a .env file in the onchain-event-handler directory with all necessary
# environment variables derived from Terraform variables.
# Reuses locals from locals.tf to avoid duplication
# Run: terraform apply -target=module.onchain_event_handler.local_file.env_file
# or: npm run generate:env (from onchain-event-handler directory)
resource "local_file" "env_file" {
  filename = "${path.module}/.env"
  content  = <<-EOT
# Generated by Terraform - do not edit manually
# Regenerate with: terraform apply -target=module.onchain_event_handler.local_file.env_file
# or: npm run generate:env (from onchain-event-handler directory)

# GCP Project Configuration
GCP_PROJECT_ID=${var.project_id}

# Multisig Configuration (JSON format, without notification destinations)
MULTISIG_CONFIG=${jsonencode(local.multisig_config_for_json)}

# Supported Chains (comma-separated)
SUPPORTED_CHAINS=${join(",", local.chains)}

# QuickNode Configuration
QUICKNODE_SIGNING_SECRET=${var.quicknode_signing_secret}
# Local development should not depend on or mutate the Terraform-managed
# production replay bucket. Override this with a real bucket only when testing
# replay persistence against GCS.
QUICKNODE_REPLAY_BUCKET=local-quicknode-replay-nonces

# Slack Configuration (shared across all multisigs)
SLACK_BOT_TOKEN=${var.slack_bot_token}
SLACK_CHANNEL_ALERTS=${local.shared_channel_ids.alerts}
SLACK_CHANNEL_EVENTS=${local.shared_channel_ids.events}
  EOT

  file_permission = "0600"
}
