# ⚠️  IMPORTANT: Terraform manages webhook CREATION only — not filter updates.
#
# If you see "unexpected response code '522'" on restapi_object.quicknode_webhook_*:
# 522 is Cloudflare's "connection timed out" (QuickNode's origin didn't respond in time).
# Retry `terraform apply`; it is often transient.
#
# If you see "429 Rate limit exceeded" on quicknode_webhook_*:
# Each webhook refresh uses multiple API calls; infra/versions.tf sets provider restapi { rate_limit = 1 }
# so Terraform does not burst QuickNode. If 429 still appears, check QuickNode status or API key quotas.
#
#
# The `filter_function` base64 blobs below are used only during initial bootstrap
# (webhook creation). Updates use `update_data` (destination only) so we never PATCH
# `filter_function` on template webhooks. `ignore_all_server_changes` reduces drift
# noise from server-only fields.
#
# CANONICAL WORKFLOWS:
#
# To UPDATE a webhook filter:
#   1. Edit the comment header in infra/quicknode-filter-functions/<webhook>.js
#   2. Run: ./bin/deploy-quicknode-filter.sh --webhook <healthcheck|governor>
#   (No pause/downtime needed — template updates are applied live.)
#
# To RECREATE a webhook (e.g. after accidental deletion):
#   1. Comment out the resource block below and run `terraform apply` to remove it
#   2. Uncomment, update filter_function blob if needed, and run `terraform apply` to recreate
#   3. Run deploy-quicknode-filter.sh to apply the current filter config on top
#
# Template-based webhooks: PATCH /webhooks/{id} must NOT include `filter_function`
# (API returns 400 — use ./bin/deploy-quicknode-filter.sh for ABI/contracts). We set
# `update_data` to only destination fields so applies can update the Cloud Function URL
# without touching the filter.


locals {
  qn_watchdog_destination_attributes = {
    url            = google_cloudfunctions2_function.watchdog_notifications.service_config[0].uri
    security_token = var.quicknode_security_token
    compression    = "none"
  }
}

# A healthcheck webhook to ensure Quicknode is operating as expected.
# We use a webhook for `MedianUpdated` events for the CELO/USD feed on our SortedOracles contract,
# Because we know with reasonable certainty that the feed will update every couple of minutes.
resource "restapi_object" "quicknode_webhook_healthcheck" {
  path = "/webhooks/rest/v1/webhooks"

  # Configure update path and method according to QuickNode API
  update_path   = "/webhooks/rest/v1/webhooks/{id}"
  update_method = "PATCH"

  # Ignore server-added fields like created_at, updated_at, sequence to prevent spurious diffs and update attempts
  # QuickNode API rejects updates to active webhooks, so this avoids unnecessary failures on subsequent applies
  ignore_all_server_changes = true

  # Serialize with governor so we don't hit QuickNode rate limit (429) when both webhooks are read/updated close together
  depends_on = [restapi_object.quicknode_webhook_governor]

  update_data = jsonencode({
    destination_attributes = local.qn_watchdog_destination_attributes
  })

  data = jsonencode({
    name    = "SortedOracles"
    network = "celo-mainnet"
    # Base64-encoded JS filter function (for debugging, simply base64-decode it)
    # Find the decoded function in ./quicknode-filter-functions/sorted-oracles.js
    filter_function = "LyoKdGVtcGxhdGU6IGV2bUFiaUZpbHRlcgphYmk6IFt7ImFub255bW91cyI6ZmFsc2UsImlucHV0cyI6W3siaW5kZXhlZCI6dHJ1ZSwiaW50ZXJuYWxUeXBlIjoiYWRkcmVzcyIsIm5hbWUiOiJ0b2tlbiIsInR5cGUiOiJhZGRyZXNzIn0seyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJ2YWx1ZSIsInR5cGUiOiJ1aW50MjU2In1dLCJuYW1lIjoiTWVkaWFuVXBkYXRlZCIsInR5cGUiOiJldmVudCJ9XQpjb250cmFjdHM6IDB4ZWZiODQ5MzUyMzlkYWNkZWNmN2M1YmE3NmQ4ZGU0MGIwNzdiN2IzMwoqLwoKY29uc3QgY29udHJhY3RzID0gWyIweGVmYjg0OTM1MjM5ZGFjZGVjZjdjNWJhNzZkOGRlNDBiMDc3YjdiMzMiXTsKLy8gT25seSBNZWRpYW5VcGRhdGVkIOKAlCBtYXRjaGVzIHRoZSBjb21tZW50IGhlYWRlciBhYm92ZSB3aGljaCB0aGUgZGVwbG95IHNjcmlwdCByZWFkcy4KLy8gVGhlIGV2bUFiaUZpbHRlciB0ZW1wbGF0ZSB1c2VzIHRoZXNlIHRlbXBsYXRlQXJncyAoYWJpICsgY29udHJhY3RzKTsgdGhpcyBKUyBib2R5IGlzCi8vIG5vdCBleGVjdXRlZCBieSBRdWlja05vZGUgZm9yIHRlbXBsYXRlLWJhc2VkIHdlYmhvb2tzLgpjb25zdCBhYmkgPSBgW3siYW5vbnltb3VzIjpmYWxzZSwiaW5wdXRzIjpbeyJpbmRleGVkIjp0cnVlLCJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6InRva2VuIiwidHlwZSI6ImFkZHJlc3MifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6InZhbHVlIiwidHlwZSI6InVpbnQyNTYifV0sIm5hbWUiOiJNZWRpYW5VcGRhdGVkIiwidHlwZSI6ImV2ZW50In1dYDsKCmZ1bmN0aW9uIG1haW4oc3RyZWFtKSB7CiAgY29uc3QgcmVzdWx0ID0gW107CgogIGNvbnN0IGhhc0NvbnRyYWN0cyA9IGNvbnRyYWN0cy5sZW5ndGggPiAwOwogIGNvbnN0IGNvbnRyYWN0U2V0ID0gaGFzQ29udHJhY3RzID8gbmV3IFNldChjb250cmFjdHMpIDogbnVsbDsKCiAgLy8gVGFyZ2V0IHRva2VuIGFkZHJlc3MgZm9yIE1lZGlhblVwZGF0ZWQgZXZlbnRzOiBDRUxPL2NVU0QgcmF0ZSBmZWVkCiAgY29uc3QgdGFyZ2V0VG9rZW5BZGRyZXNzID0KICAgICIweDc2NWRlODE2ODQ1ODYxZTc1YTI1ZmNhMTIyYmI2ODk4YjhiMTI4MmEiLnRvTG93ZXJDYXNlKCk7CgogIGZvciAoY29uc3QgYmxvY2sgb2Ygc3RyZWFtLmRhdGEpIHsKICAgIGNvbnN0IGZpbHRlcmVkUmVjZWlwdHMgPSBibG9jay5yZWNlaXB0cy5tYXAoKHJlY2VpcHQpID0+IHsKICAgICAgY29uc3QgbG9ncyA9IGNvbnRyYWN0U2V0CiAgICAgICAgPyByZWNlaXB0LmxvZ3MuZmlsdGVyKChsb2cpID0+CiAgICAgICAgICAgIGNvbnRyYWN0U2V0Lmhhcyhsb2cuYWRkcmVzcy50b0xvd2VyQ2FzZSgpKSwKICAgICAgICAgICkKICAgICAgICA6IHJlY2VpcHQubG9nczsKCiAgICAgIHJldHVybiB7IC4uLnJlY2VpcHQsIGxvZ3MgfTsKICAgIH0pOwoKICAgIGNvbnN0IGRlY29kZWRSZWNlaXB0cyA9IGRlY29kZUVWTVJlY2VpcHRzKGZpbHRlcmVkUmVjZWlwdHMsIFthYmldKTsKCiAgICBmb3IgKGNvbnN0IHJlY2VpcHQgb2YgZGVjb2RlZFJlY2VpcHRzKSB7CiAgICAgIGlmIChyZWNlaXB0LmRlY29kZWRMb2dzICYmIHJlY2VpcHQuZGVjb2RlZExvZ3MubGVuZ3RoID4gMCkgewogICAgICAgIGZvciAoY29uc3QgbG9nIG9mIHJlY2VpcHQuZGVjb2RlZExvZ3MpIHsKICAgICAgICAgIC8vIE9ubHkgaW5jbHVkZSBNZWRpYW5VcGRhdGVkIGV2ZW50cyB3aXRoIHRoZSBzcGVjaWZpYyB0b2tlbiBhZGRyZXNzCiAgICAgICAgICBpZiAoCiAgICAgICAgICAgIGxvZy5uYW1lID09PSAiTWVkaWFuVXBkYXRlZCIgJiYKICAgICAgICAgICAgbG9nLnRva2VuLnRvTG93ZXJDYXNlKCkgPT09IHRhcmdldFRva2VuQWRkcmVzcwogICAgICAgICAgKSB7CiAgICAgICAgICAgIHJlc3VsdC5wdXNoKHsKICAgICAgICAgICAgICB0cmFuc2FjdGlvbkhhc2g6IHJlY2VpcHQudHJhbnNhY3Rpb25IYXNoLAogICAgICAgICAgICAgIC4uLmxvZywKICAgICAgICAgICAgfSk7CiAgICAgICAgICB9CiAgICAgICAgfQogICAgICB9CiAgICB9CiAgfQoKICByZXR1cm4gcmVzdWx0Lmxlbmd0aCA+IDAgPyB7IHJlc3VsdCB9IDogbnVsbDsKfQo="
    status          = "active"

    destination_attributes = local.qn_watchdog_destination_attributes
  })

  lifecycle {
    create_before_destroy = true
  }
}

# Watches for new events on the Governor contract https://celoscan.io/address/0x47036d78bB3169b4F5560dD77BF93f4412A59852
resource "restapi_object" "quicknode_webhook_governor" {
  path = "/webhooks/rest/v1/webhooks"

  # Configure update path and method according to QuickNode API
  update_path   = "/webhooks/rest/v1/webhooks/{id}"
  update_method = "PATCH"

  # Ignore server-added fields like created_at, updated_at, sequence to prevent spurious diffs and update attempts
  # QuickNode API rejects updates to active webhooks, so this avoids unnecessary failures on subsequent applies
  ignore_all_server_changes = true

  update_data = jsonencode({
    destination_attributes = local.qn_watchdog_destination_attributes
  })

  data = jsonencode({
    name    = "MentoGovernor"
    network = "celo-mainnet"
    # Base64-encoded JS filter function (for debugging, simply base64-decode it)
    # Find the decoded function in ./quicknode-filter-functions/governor.js
    filter_function = "LyoKdGVtcGxhdGU6IGV2bUFiaUZpbHRlcgphYmk6IFt7ImFub255bW91cyI6ZmFsc2UsImlucHV0cyI6W3siaW5kZXhlZCI6ZmFsc2UsImludGVybmFsVHlwZSI6InVpbnQyNTYiLCJuYW1lIjoicHJvcG9zYWxJZCIsInR5cGUiOiJ1aW50MjU2In1dLCJuYW1lIjoiUHJvcG9zYWxDYW5jZWxlZCIsInR5cGUiOiJldmVudCJ9LHsiYW5vbnltb3VzIjpmYWxzZSwiaW5wdXRzIjpbeyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJwcm9wb3NhbElkIiwidHlwZSI6InVpbnQyNTYifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6InByb3Bvc2VyIiwidHlwZSI6ImFkZHJlc3MifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzW10iLCJuYW1lIjoidGFyZ2V0cyIsInR5cGUiOiJhZGRyZXNzW10ifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2W10iLCJuYW1lIjoidmFsdWVzIiwidHlwZSI6InVpbnQyNTZbXSJ9LHsiaW5kZXhlZCI6ZmFsc2UsImludGVybmFsVHlwZSI6InN0cmluZ1tdIiwibmFtZSI6InNpZ25hdHVyZXMiLCJ0eXBlIjoic3RyaW5nW10ifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJieXRlc1tdIiwibmFtZSI6ImNhbGxkYXRhcyIsInR5cGUiOiJieXRlc1tdIn0seyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJzdGFydEJsb2NrIiwidHlwZSI6InVpbnQyNTYifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6ImVuZEJsb2NrIiwidHlwZSI6InVpbnQyNTYifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJzdHJpbmciLCJuYW1lIjoiZGVzY3JpcHRpb24iLCJ0eXBlIjoic3RyaW5nIn1dLCJuYW1lIjoiUHJvcG9zYWxDcmVhdGVkIiwidHlwZSI6ImV2ZW50In0seyJhbm9ueW1vdXMiOmZhbHNlLCJpbnB1dHMiOlt7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6InByb3Bvc2FsSWQiLCJ0eXBlIjoidWludDI1NiJ9XSwibmFtZSI6IlByb3Bvc2FsRXhlY3V0ZWQiLCJ0eXBlIjoiZXZlbnQifSx7ImFub255bW91cyI6ZmFsc2UsImlucHV0cyI6W3siaW5kZXhlZCI6ZmFsc2UsImludGVybmFsVHlwZSI6InVpbnQyNTYiLCJuYW1lIjoicHJvcG9zYWxJZCIsInR5cGUiOiJ1aW50MjU2In0seyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJldGEiLCJ0eXBlIjoidWludDI1NiJ9XSwibmFtZSI6IlByb3Bvc2FsUXVldWVkIiwidHlwZSI6ImV2ZW50In1dCmNvbnRyYWN0czogMHg0NzAzNmQ3OGJiMzE2OWI0ZjU1NjBkZDc3YmY5M2Y0NDEyYTU5ODUyCiovCgpjb25zdCBjb250cmFjdHMgPSBbIjB4NDcwMzZkNzhiYjMxNjliNGY1NTYwZGQ3N2JmOTNmNDQxMmE1OTg1MiJdOwovLyBPbmx5IHRoZSA0IGV2ZW50cyB0aGUgYXBwIGhhbmRsZXMg4oCUIG1hdGNoZXMgdGhlIGNvbW1lbnQgaGVhZGVyIGFib3ZlLgovLyBUaGUgSlMgYm9keSBpcyBub3QgZXhlY3V0ZWQgYnkgUXVpY2tOb2RlIGZvciB0ZW1wbGF0ZS1iYXNlZCB3ZWJob29rcy4KY29uc3QgYWJpID0gYFt7ImFub255bW91cyI6ZmFsc2UsImlucHV0cyI6W3siaW5kZXhlZCI6ZmFsc2UsImludGVybmFsVHlwZSI6InVpbnQyNTYiLCJuYW1lIjoicHJvcG9zYWxJZCIsInR5cGUiOiJ1aW50MjU2In1dLCJuYW1lIjoiUHJvcG9zYWxDYW5jZWxlZCIsInR5cGUiOiJldmVudCJ9LHsiYW5vbnltb3VzIjpmYWxzZSwiaW5wdXRzIjpbeyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJwcm9wb3NhbElkIiwidHlwZSI6InVpbnQyNTYifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6InByb3Bvc2VyIiwidHlwZSI6ImFkZHJlc3MifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzW10iLCJuYW1lIjoidGFyZ2V0cyIsInR5cGUiOiJhZGRyZXNzW10ifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2W10iLCJuYW1lIjoidmFsdWVzIiwidHlwZSI6InVpbnQyNTZbXSJ9LHsiaW5kZXhlZCI6ZmFsc2UsImludGVybmFsVHlwZSI6InN0cmluZ1tdIiwibmFtZSI6InNpZ25hdHVyZXMiLCJ0eXBlIjoic3RyaW5nW10ifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJieXRlc1tdIiwibmFtZSI6ImNhbGxkYXRhcyIsInR5cGUiOiJieXRlc1tdIn0seyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJzdGFydEJsb2NrIiwidHlwZSI6InVpbnQyNTYifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6ImVuZEJsb2NrIiwidHlwZSI6InVpbnQyNTYifSx7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJzdHJpbmciLCJuYW1lIjoiZGVzY3JpcHRpb24iLCJ0eXBlIjoic3RyaW5nIn1dLCJuYW1lIjoiUHJvcG9zYWxDcmVhdGVkIiwidHlwZSI6ImV2ZW50In0seyJhbm9ueW1vdXMiOmZhbHNlLCJpbnB1dHMiOlt7ImluZGV4ZWQiOmZhbHNlLCJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6InByb3Bvc2FsSWQiLCJ0eXBlIjoidWludDI1NiJ9XSwibmFtZSI6IlByb3Bvc2FsRXhlY3V0ZWQiLCJ0eXBlIjoiZXZlbnQifSx7ImFub255bW91cyI6ZmFsc2UsImlucHV0cyI6W3siaW5kZXhlZCI6ZmFsc2UsImludGVybmFsVHlwZSI6InVpbnQyNTYiLCJuYW1lIjoicHJvcG9zYWxJZCIsInR5cGUiOiJ1aW50MjU2In0seyJpbmRleGVkIjpmYWxzZSwiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJldGEiLCJ0eXBlIjoidWludDI1NiJ9XSwibmFtZSI6IlByb3Bvc2FsUXVldWVkIiwidHlwZSI6ImV2ZW50In1dYDsKCmZ1bmN0aW9uIG1haW4oc3RyZWFtKSB7CiAgY29uc3QgcmVzdWx0ID0gW107CgogIGNvbnN0IGhhc0NvbnRyYWN0cyA9IGNvbnRyYWN0cy5sZW5ndGggPiAwOwogIGNvbnN0IGNvbnRyYWN0U2V0ID0gaGFzQ29udHJhY3RzID8gbmV3IFNldChjb250cmFjdHMpIDogbnVsbDsKCiAgZm9yIChjb25zdCBibG9jayBvZiBzdHJlYW0uZGF0YSkgewogICAgY29uc3QgZmlsdGVyZWRSZWNlaXB0cyA9IGJsb2NrLnJlY2VpcHRzLm1hcCgocmVjZWlwdCkgPT4gewogICAgICBjb25zdCBsb2dzID0gY29udHJhY3RTZXQKICAgICAgICA/IHJlY2VpcHQubG9ncy5maWx0ZXIoKGxvZykgPT4KICAgICAgICAgICAgY29udHJhY3RTZXQuaGFzKGxvZy5hZGRyZXNzLnRvTG93ZXJDYXNlKCkpLAogICAgICAgICAgKQogICAgICAgIDogcmVjZWlwdC5sb2dzOwoKICAgICAgcmV0dXJuIHsgLi4ucmVjZWlwdCwgbG9ncyB9OwogICAgfSk7CgogICAgY29uc3QgZGVjb2RlZFJlY2VpcHRzID0gZGVjb2RlRVZNUmVjZWlwdHMoZmlsdGVyZWRSZWNlaXB0cywgW2FiaV0pOwoKICAgIGZvciAoY29uc3QgcmVjZWlwdCBvZiBkZWNvZGVkUmVjZWlwdHMpIHsKICAgICAgaWYgKHJlY2VpcHQuZGVjb2RlZExvZ3MgJiYgcmVjZWlwdC5kZWNvZGVkTG9ncy5sZW5ndGggPiAwKSB7CiAgICAgICAgZm9yIChjb25zdCBsb2cgb2YgcmVjZWlwdC5kZWNvZGVkTG9ncykgewogICAgICAgICAgcmVzdWx0LnB1c2goewogICAgICAgICAgICB0cmFuc2FjdGlvbkhhc2g6IHJlY2VpcHQudHJhbnNhY3Rpb25IYXNoLAogICAgICAgICAgICAuLi5sb2csCiAgICAgICAgICB9KTsKICAgICAgICB9CiAgICAgIH0KICAgIH0KICB9CgogIHJldHVybiByZXN1bHQubGVuZ3RoID4gMCA/IHsgcmVzdWx0IH0gOiBudWxsOwp9Cg=="
    status          = "active"

    destination_attributes = local.qn_watchdog_destination_attributes
  })

  lifecycle {
    create_before_destroy = true
  }
}
