import type { PegMonitoringResponse } from "@/lib/peg-monitoring";

export const PEG_FIXTURE_PRODUCED_AT = 1_800_000_000;
export const PEG_FIXTURE_CHAIN_ID = 137;
export const PEG_FIXTURE_POOL_ADDRESS =
  "0xcd8c6811d975981f57e7fb32e59f0bee66af3201";
const fixture: PegMonitoringResponse = {
  schemaVersion: 1,
  approvedActivePolicyVersion:
    "europ-2026-07-22-v1-a69b99aad61649957a2639dc8348b05f",
  producedPolicyVersion: "europ-2026-07-22-v1-a69b99aad61649957a2639dc8348b05f",
  policySlot: "active",
  producedAt: PEG_FIXTURE_PRODUCED_AT,
  rolloverAckExpectedSeconds: 300,
  packages: [
    {
      asset: "europ-schuman",
      peg: "EUR",
      coverageClass: "cex-book+indexed-pool",
      tokenRefs: [
        {
          chainId: PEG_FIXTURE_CHAIN_ID,
          address: "0x888883b5f5d21fb10dfeb70e8f9722b9fb0e5e51",
        },
      ],
      policy: {
        target: 1,
        warnDeviationBps: 25,
        criticalDeviationBps: 50,
        premiumWarnBps: 25,
        warnSustainSeconds: 600,
        criticalSustainSeconds: 1200,
        durationQuantile: 0.2,
        minimumCoverageFraction: 0.8,
        blindConsecutivePolls: 10,
        permanentlyDeadSeconds: 259200,
        structuralWarnFraction: 0.8,
        freshnessGraceSeconds: 300,
        deepVenueSource: "bitvavo_eur",
      },
      structural: {
        blind: false,
        blindConsecutivePolls: 0,
        structuralSaturation: 0.42,
        structuralQuerySaturated: false,
        indexedPoolReachable: true,
        counterpartyCount: 7,
      },
      monitors: [
        {
          chainId: PEG_FIXTURE_CHAIN_ID,
          poolAddress: PEG_FIXTURE_POOL_ADDRESS,
          rateFeedId: "0xc22418a83dfc262b10a1f57e25309db83e7ea79e",
          monitoredTokenAddress: "0x888883b5f5d21fb10dfeb70e8f9722b9fb0e5e51",
          indexedPoolReachable: true,
          structuralSaturation: 0.42,
          structuralQuerySaturated: false,
          counterpartyCount: 7,
          breaker: {
            id: "europ-value-delta",
            address: "0x4444444444444444444444444444444444444444",
            enabled: true,
            kind: "VALUE_DELTA",
            status: "OK",
            tradingMode: 0,
            effectiveRateChangeThreshold: "5000000000000000000000",
            referenceValue: "1000000000000000000000000",
            lastMedianRate: "998000000000000000000000",
            thresholdScale: "fixidity-1e24",
            lastUpdatedAt: PEG_FIXTURE_PRODUCED_AT - 20,
            lastStatusUpdatedAt: PEG_FIXTURE_PRODUCED_AT - 20,
          },
        },
      ],
      sources: [
        {
          id: "bitvavo_eur",
          provider: "bitvavo",
          pair: "EUROP-EUR",
          baseCurrency: "EUROP",
          quoteCurrency: "EUR",
          registryRole: "primary",
          authority: "deep",
          convertVia: null,
          policy: {
            referenceSizeCap: 50000,
            pollIntervalSeconds: 30,
            staleAfterSeconds: 120,
            spreadEnvelopeBps: 30,
            conversionErrorBps: 0,
          },
          listingState: null,
          listingCheckedAt: null,
          healthy: true,
          venueState: "ok",
          observationAt: PEG_FIXTURE_PRODUCED_AT - 5,
          fetchedAt: PEG_FIXTURE_PRODUCED_AT - 4,
          lastTradeAt: PEG_FIXTURE_PRODUCED_AT - 12,
          executablePrice: 0.9965,
          filledFraction: 1,
          capped: false,
          referenceSize: 50000,
          bid: 0.996,
          ask: 0.997,
          spreadBps: 10.04,
          deviationBps: 35,
          premiumBps: 0,
        },
        {
          id: "kraken_eur",
          provider: "kraken",
          pair: "EUROP/EUR",
          baseCurrency: "EUROP",
          quoteCurrency: "EUR",
          registryRole: "secondary",
          authority: "secondary",
          convertVia: null,
          policy: {
            referenceSizeCap: 50000,
            pollIntervalSeconds: 60,
            staleAfterSeconds: 300,
            spreadEnvelopeBps: 75,
            conversionErrorBps: 0,
          },
          listingState: null,
          listingCheckedAt: null,
          healthy: true,
          venueState: "ok",
          observationAt: PEG_FIXTURE_PRODUCED_AT - 8,
          fetchedAt: PEG_FIXTURE_PRODUCED_AT - 7,
          lastTradeAt: PEG_FIXTURE_PRODUCED_AT - 15,
          executablePrice: 0.9968,
          filledFraction: 1,
          capped: false,
          referenceSize: 50000,
          bid: 0.9963,
          ask: 0.9973,
          spreadBps: 10.03,
          deviationBps: 32,
          premiumBps: 0,
        },
        {
          id: "kraken_usd",
          provider: "kraken",
          pair: "EUROP/USD",
          baseCurrency: "EUROP",
          quoteCurrency: "USD",
          registryRole: "display",
          authority: "display",
          convertVia: {
            chainId: PEG_FIXTURE_CHAIN_ID,
            rateFeedId: "0xec57482aa55e3ad026c315a0e4a692b776c318ca",
            fromCurrency: "USD",
            toCurrency: "EUR",
          },
          policy: {
            referenceSizeCap: 50000,
            pollIntervalSeconds: 300,
            staleAfterSeconds: 600,
            spreadEnvelopeBps: 100,
            conversionErrorBps: 30,
          },
          listingState: null,
          listingCheckedAt: null,
          healthy: true,
          venueState: "ok",
          observationAt: PEG_FIXTURE_PRODUCED_AT - 20,
          fetchedAt: PEG_FIXTURE_PRODUCED_AT - 19,
          lastTradeAt: PEG_FIXTURE_PRODUCED_AT - 25,
          executablePrice: 0.9971,
          filledFraction: 1,
          capped: false,
          referenceSize: 50000,
          bid: 0.9966,
          ask: 0.9976,
          spreadBps: 10.03,
          deviationBps: 29,
          premiumBps: 0,
        },
      ],
    },
  ],
};
export function makePegMonitoringResponse(
  overrides: Partial<PegMonitoringResponse> = {},
): PegMonitoringResponse {
  return { ...fixture, ...overrides };
}
