name: "Trunk: Code Quality"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk:
    name: Trunk Check
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.trunk/setup-ci
      - uses: trunk-io/trunk-action@v1
        with:
          arguments: --all
